/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package os.assistant;

import java.awt.Color;
import java.awt.List;
import java.util.ArrayList;
import javax.swing.BoxLayout;

/**
 *
 * @author Daniel
 */
public class SkillList extends javax.swing.JPanel {

    /**
     * Creates new form SkillList
     */
    public SkillList() {
        //initComponents();
        this.setLayout(new BoxLayout(this, BoxLayout.Y_AXIS));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private ArrayList<SkillPanel> list = new ArrayList<>();

    public void addSkill(SkillPanel s) {
        if (!list.contains(s)) {
            list.add(s);
            this.add(s);
        }
        else {
            SkillStats stat = s.getStat();
            list.get(list.indexOf(s)).setStats(stat);
        }
        
    }
    
   
    
    public void addSkillAll(java.util.List<SkillStats> list) {
        for(SkillStats item : list) {
            SkillPanel panel = new SkillPanel();
            panel.setStats(item);
            panel.setVisible(true);
            panel.setSize(200, 150);
            addSkill(panel);
            
        }
    }
    
    public SkillPanel find(String skillName) {
        int index = list.indexOf(skillName);
        if (index >= 0)
         return list.get(index);
        return null;
    }
    
    public void clear() {
        this.removeAll();
        this.list.clear();
    }
    
    
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
